### ISSUE TITLE
About processing MegaDepth dataset to MegaDepth-release-light

### ISSUE THREAD

**Issue by AndreyFang** [qianqianwang68/caps#11]
Thanks for your excellent work!
I am doing some research based on your work, but I ran into some problems with the dataset. I noticed that your images in your dataset have been scaled to a fixed size which should caused the differences from the original R, right? I have searched many ways to caculate new R and t, but I can't get to your data. Could you please tell me how to calculate the scaled R? Looking forward to your reply.

**Comment by jeannotes** [comment]
@qianqianwang68  hope that you can release your preprocess script.

**Comment by qianqianwang68** [comment]
[script.zip](https://github.com/qianqianwang68/caps/files/9144593/script.zip)
Please find attached the processing code. Running 'process_all.py' should be able to generate the data like in CAPS. To run this file you would need to prepare colmap reconstruction as input.

**Comment by jeannotes** [comment]
thanks

**Comment by jeannotes** [comment]
@qianqianwang68 hi, I can see that you opensource train dataset, can you release test and val dataset, we need to download all the data which is very large, thanks for that.

**Comment by jeannotes** [comment]
@qianqianwang68 seems that when you process image, didn't use any depth info, why need reconstruction input?

**Comment by qianqianwang68** [comment]
That's because we still need the camera poses from the reconstruction. But you are right depth info is not needed.

**Comment by FlyFish-space** [comment]
> [script.zip](https://github.com/qianqianwang68/caps/files/9144593/script.zip) Please find attached the processing code. Running 'process_all.py' should be able to generate the data like in CAPS. To run this file you would need to prepare colmap reconstruction as input. My apologies if you find the code messy (I did not have much time to clean it), but let me know you have any question.

Thank you for your open preprocessing code. I have read each code and understood their functions, but can you tell me in what order to run these codes to reproduce your dataset partition method？ thanks！
