### ISSUE TITLE
Reproduce the test results of caps

### ISSUE THREAD

**Issue by FlyFish-space** [qianqianwang68/caps#13]
First of all, thank you very much for your outstanding work！
1.I trained the network of caps from scratch and tested it with the code provided by D2 Net. The result is better than the figure in the article.
2.Could you please provide the complete test code for megadepth and scannet？There is no code in the file for how to obtain megadepth/scanet descriptors

**Comment by qianqianwang68** [comment]
Hi,

1. Interesting. Did you train with different hyperparameters? How much better the result is compared to that reported in the paper?
2. The test code for megadepth and scannet can be found here: https://github.com/qianqianwang68/caps/tree/master/test. Sorry, the code is uncleaned. To run this evaluation, you would need to prepare keypoints and descriptors. The code only evaluates on megadepth but the code for scannet should be basically the same. The two zip files provide the test pairs we used for evaluation. Let me know if you have any questions.

**Comment by qianqianwang68** [comment]
Sorry, I misread your second question. To obtain the descriptors you could run https://github.com/qianqianwang68/caps/blob/master/extract_features.py, and you could also change the SIFT keypoints to superpoint keypoints. Meanwhile, I will try to find my script for extracting features on scannet and megadepth.
