### ISSUE TITLE
extracting features on scannet and megadepth

### ISSUE THREAD

**Issue by Gaotianhong** [qianqianwang68/caps#16]
Thank you very much for your work!

How can I find script for extracting features on scannet and megadepth？

_Originally posted by @qianqianwang68 in https://github.com/qianqianwang68/caps/issues/13#issuecomment-1264499264_

**Comment by Gaotianhong** [comment]
I have solved it

**Comment by Freeda0517** [comment]
I also encountered the same problem. How did you solve it?
