### ISSUE TITLE
Store a copy of dataset and weight on BaiduYun

### ISSUE THREAD

**Issue by zhuohoudeputao** [qianqianwang68/caps#2]
Due to well-known reasons, google drive is difficult to access in China. Can you store a copy of the dataset and weight file on BaiduYun (A web drive in China mainland)? It will be helpful for us. Thanks a lot!

**Comment by Johnzdh** [comment]
I uploaded to BaiduYun. But it limited to share the link. If you still need it, you could send me a email.

**Comment by ghzhangnj** [comment]
从谷歌上下载下来，解压后 只有一个13G+ 的大文件

**Comment by qianqianwang68** [comment]
@zhuohoudeputao, sorry for the late reply. I've updated a BaiduYun link in README.md. Please check it out.
@Johnzdh, thank you for spreading the dataset!
@ghzhangnj 你解压的方式对吗? 可以在命令行里试一下tar -xvf CAPS-MegaDepth-release-light.tar，解压出来应该是一个文件夹，包含图片和标注等等。

**Comment by ghzhangnj** [comment]
谢谢， 可以了
