### ISSUE TITLE
Problem with grayscale images

### ISSUE THREAD

**Issue by jeethesh-pai** [qianqianwang68/caps#5]
Hallo caps team,

I have a doubt on drawing inference on images which are grayscale. Is it possible to get feature descriptor using CAPS network for a grayscale image. I get an error stating the pretrained model weights are incompatible for 1-channel inputs ?

Thanks 
Jeethesh

**Comment by qianqianwang68** [comment]
Hi you can try to expand the grayscale image into a color image by repeating the color channel 3 times and stacking them together. Hope this helps.

**Comment by jeethesh-pai** [comment]
Hi, Thank you for your quicl reply. 
I tried that but the match is not optimal. Many keypoints are not matched. Is there a way to train with grayscale image so that i can increase the correspondence match?

**Comment by qianqianwang68** [comment]
Yes, you can turn the color images in the provided dataset into gray-scale images and retrain/finetune the model.

**Comment by jeethesh-pai** [comment]
Thank you so much replies. I will try training with grayscale images.
